### ISSUE TITLE
NoMethodError: undefined method `failure_count' for nil:NilClass

### ISSUE THREAD

**Issue by ghost** [Arduino-CI/action#27]
The error

```
NoMethodError: undefined method `failure_count' for nil:NilClass
```
appears when I run under docker. I haven't tried this under Github Actions yet... partly because I have this error.
My library is fairly simple, the example app builds happily under Arduino IDE. I have no unit tests. Here's my docker command:

```
docker run --rm \
  -v "$HOME/Arduino/libraries:/root/Arduino/libraries" \
  --workdir /root/Arduino/libraries/MultiModuleLog \
  --env EXPECT_EXAMPLES=Y \
  ghcr.io/arduino-ci/action/ubuntu

```
and here is the error in the log (full log is attached).

```
================================================================================
|  Compilation of example sketches
====
Using configuration override from examples...                             <none>

Discovered example sketch...                                    LoggerSample.ino
Using configuration override from example...                              <none>
Default config, platforms matching architectures in library.properties... 
    esp32
...Default config, platforms matching architectures in library.properties       
Board package esp32:esp32 has a defined URL...                                 ✓
Installing board package esp32:esp32...                                        ✗
This may indicate a problem with your configuration; halting here
bundler: failed to load command: /action/bundle/ruby/2.6.0/bin/arduino_ci.rb (/action/bundle/ruby/2.6.0/bin/arduino_ci.rb)
NoMethodError: undefined method `failure_count' for nil:NilClass
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:111:in `terminate'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.6.2/lib/arduino_ci/logger.rb:137:in `perform_action'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.6.2/lib/arduino_ci/logger.rb:170:in `assure'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:207:in `block in install_all_packages'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:202:in `each'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:202:in `install_all_packages'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:546:in `block in perform_example_compilation_tests'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:516:in `each'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:516:in `perform_example_compilation_tests'
  /action/bundle/ruby/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:609:in `<top (required)>'
  /action/bundle/ruby/2.6.0/bin/arduino_ci.rb:23:in `load'
  /action/bundle/ruby/2.6.0/bin/arduino_ci.rb:23:in `<top (required)>
```

It looks like it failed to install the esp32 board package. It did take a long time trying, I didn't stay to watch so I can't say how long, likely more than 30 minutes though.

This is my first time using `arduino-ci` so I might have screwed up something, but at this stage I don't know what it might be.
My project is in [https://github.com/RogerParkinson/MultiModuleLog](https://github.com/RogerParkinson/MultiModuleLog)

[arduino-ci.log](https://github.com/Arduino-CI/action/files/13667232/arduino-ci.log)

**Comment by higaski** [comment]
Same issue for me, log attached
[logs_6.zip](https://github.com/Arduino-CI/action/files/14124407/logs_6.zip)
